[tool.poetry]
name = "export-job"
version = "4.1.0"
description = ""
authors = ["Mingfei Shao <mshao1@uchicago.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
gen3 = { git = "https://github.com/uc-cdis/gen3sdk-python.git", branch = "fix/drs-pull-manifest-validation" }
boto3 = "^1.0.0"
cdiserrors = "^1.0.0"
urllib3 = "<=2.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
